name: Deploy to Vercel

on:
  push:
    branches: [master] # or your deployment branch
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: too-fishy
  PROJECT_PATH: .
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Export-And-Deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.1
          use-dotnet: false

      - name: Web Build
        run: |
          mkdir -v -p dist
          godot --headless --verbose --export-release "Web" "./dist/index.html"

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy dist --prod --token=${{ secrets.VERCEL_TOKEN }}
