name: Deploy to Vercel

on:
  push:
    branches: [master] # or your deployment branch
  workflow_dispatch:

env:
  GODOT_VERSION: 4.4.1
  EXPORT_NAME: too-fishy
  PROJECT_PATH: .
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  Export-And-Deploy:
    runs-on: ubuntu-22.04    
    container:
      image: barichello/godot-ci:4.4.1
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Godot
        uses: chickensoft-games/setup-godot@v1
        with:
          version: 4.4.1
          use-dotnet: false
          
      - name: Setup
        run: |
          mkdir -v -p ~/.local/share/godot/export_templates/
          mv /root/.local/share/godot/export_templates/${GODOT_VERSION}.stable ~/.local/share/godot/export_templates/${GODOT_VERSION}.stable
      - name: Web Build
        run: |
          mkdir -v -p build/web
          EXPORT_DIR="$(readlink -f build)"
          cd $PROJECT_PATH
          godot --headless --verbose --export-release "Web" "$EXPORT_DIR/web/index.html"
          
      - name: Copy build files to dist
        run: |
          mkdir -p dist/web
          cp -r build/web/* dist/web/
          
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Vercel CLI
        run: npm install --global vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=production --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel
        run: vercel deploy dist --prod --token=${{ secrets.VERCEL_TOKEN }}
